"""
main.py
-------
The entry point of the backend. This is what `uvicorn app.main:app` runs.

Responsibilities, and only these, on purpose:
1. Create the FastAPI application object.
2. Make sure the database tables exist.
3. Allow the frontend (running on a different port) to call us (CORS).
4. Wire up the routers (currently just health).

Business logic (readiness scoring, risk rules, governance policies...)
will live in their own modules in later phases -- main.py stays thin
forever, it's just the "switchboard".
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .database import Base, engine
from .routers import health

# Create any tables defined in models.py that don't exist yet.
# In a real production system you'd use migrations (e.g. Alembic) instead
# of this, so that changing a table doesn't risk losing data. For a local
# learning MVP with a disposable SQLite file, this is the simplest honest
# option -- we'll call out explicitly if/when we outgrow it.
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="AI Bridge API",
    description=(
        "Backend for AI Bridge — an Enterprise AI Infrastructure platform. "
        "Phase 1: Foundation only (no governance/risk logic yet)."
    ),
    version="0.1.0",
)

# Browsers block a webpage on one origin (http://localhost:5173, the Vite
# dev server) from calling an API on a different origin (http://localhost:8000)
# unless the API explicitly allows it. This is CORS (Cross-Origin Resource
# Sharing). In production you'd list your real frontend domain here instead
# of localhost.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router, prefix="/api", tags=["health"])


@app.get("/")
def root():
    return {
        "message": "AI Bridge API is running.",
        "docs": "Visit /docs for the interactive API explorer (auto-generated by FastAPI).",
    }
